name: Test Field Processor
on: [push] # Запуск при кожному оновленні коду

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install geopandas gspread google-auth
      - name: Run script
        env:
          GCP_JSON: ${{ secrets.GCP_JSON }}
        run: |
          python field_processor.py
